[package]
name = "syllabus"
version.workspace = true
keywords.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true

[dependencies]
rusaint = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.143"
futures = "0.3.31"
serde = "1.0.219"

[lints]
workspace = true
